server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    user:
      name: configuser
      password: configpass123
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tito-67ai/escuela-config.git
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true